# Neo4j configuration file
dbms.usage_report.enabled=false

server.jvm.additional=--add-modules jdk.incubator.vector

db.query.default_language=CYPHER_25

dbms.security.procedures.unrestricted=ai.*,genai.*

server.memory.pagecache.size=512M

server.default_listen_address=0.0.0.0
server.directories.plugins=/plugins
server.directories.logs=/logs
