services:
  gateway:
    image: nginx:1.28.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - nextjs
      - fastapi
    networks:
      - gateway

  nextjs:
    build: './frontend'
    environment:
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      INTERNAL_API_BASE_URL: ${INTERNAL_API_BASE_URL}
    networks:
      - gateway

  fastapi:
    build: './backend'
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1"]
    depends_on:
      redis:
        condition: service_healthy
      neo4j-init:
        condition: service_completed_successfully
    networks:
      - gateway
      - database

  redis:
    image: redis:8.6
    command: redis-server --save 60 1 --requirepass ${REDIS_PASSWORD} --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database

  neo4j-init:
    build: ./neo4j-init
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      HF_EMBEDDING_MODEL: ${HF_EMBEDDING_MODEL}
    volumes:
      - ${PROJECTS_DIR}:/data
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - database

  neo4j:
    image: neo4j:2026.01.4
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"
      NEO4J_PLUGINS: '["genai"]'
    depends_on:
      - tei-embeddings
    volumes:
      - neo4j-data:/data
      - neo4j-plugins:/plugins
      - ./neo4j/neo4j.conf:/conf/neo4j.conf
      - ./neo4j/genai.conf:/conf/genai.conf
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database
      - embeddings

  tei-embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    command: --model-id ${HF_EMBEDDING_MODEL}
    volumes:
      - embeddings-data:/data
    networks:
      - embeddings

volumes:
  trace-data:
  embeddings-data:
  redis-data:
  neo4j-data:
  neo4j-plugins:

networks:
  gateway:
  database:
  embeddings:
