services:
  nextjs:
    build:
      context: './frontend'
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      INTERNAL_API_BASE_URL: ${INTERNAL_API_BASE_URL}
    networks:
      - gateway

  fastapi:
    build: './backend'
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1"]
    depends_on:
      redis:
        condition: service_healthy
      neo4j-init:
        condition: service_completed_successfully
    networks:
      - gateway
      - database

  redis:
    image: redis:8.6
    command: redis-server --save 60 1 --requirepass ${REDIS_PASSWORD} --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database

  neo4j-init:
    build: ./neo4j-init
    environment:
      GITEA_PAT: ${GITEA_PAT}
      DATA_BASE_URL: ${DATA_BASE_URL}
      DATA_VERSION: ${DATA_VERSION}
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      HF_EMBEDDING_MODEL: ${HF_EMBEDDING_MODEL}
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - database

  neo4j:
    image: neo4j:2026.01.4
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"
      NEO4J_PLUGINS: '["genai"]'
    depends_on:
      - tei-embeddings
    volumes:
      - neo4j-data:/data
      - neo4j-plugins:/plugins
      - ./neo4j/neo4j.conf:/conf/neo4j.conf
      - ./neo4j/genai.conf:/conf/genai.conf
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - database
      - embeddings

  tei-embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    command: --model-id ${HF_EMBEDDING_MODEL}
    volumes:
      - embeddings-data:/data
    networks:
      - embeddings

volumes:
  embeddings-data:
  redis-data:
  neo4j-data:
  neo4j-plugins:

networks:
  gateway:
  database:
  embeddings:
